### ISSUE TITLE
フレンドが参加しているワールドが見れない

### ISSUE THREAD

**Issue by syarurunoin** [fa0311/vrc_manager#184]
### Steps to reproduce

1 「オンラインのフレンド」から緑ステータスの人をタップする
2 「エラーが発生しました」と表示され、たくさんのログが表示される

### Where you downloaded the app

Google Play Store

### Relevant error message output

```shell
{
     "appName": "VRCManager",
     "buildNumber": "24",
     "buildSignature": "3011F3A7E9D21DA433BAF9EC0FF9EDCE533E7E5C",
     "installerStore": "com.android.vending",
     "packageName": "com.yuki0311.vrc_manager",
     "version": "5.0.3",
     "deviceInfo": {
          "product": "SH-RM15",
          "supportedAbis": [
               "arm64-v8a",
               "armeabi-v7a",
               "armeabi"
          ],
          "serialNumber": "unknown",
          "displayMetrics": {
               "xDpi": 435.4280090332031,
               "widthPx": 1080.0,
               "heightPx": 2280.0,
               "yDpi": 435.4280090332031
          },
          "supported32BitAbis": [
               "armeabi-v7a",
               "armeabi"
          ],
          "display": "03.00.05",
          "type": "user",
          "isPhysicalDevice": true,
          "version": {
               "baseOS": "",
               "securityPatch": "2022-10-01",
               "sdkInt": 31,
               "release": "12",
               "codename": "REL",
               "previewSdkInt": 0,
               "incremental": "03.00.05"
          },
          "systemFeatures": [
               "android.hardware.sensor.proximity",
               "android.software.adoptable_storage",
               "android.hardware.sensor.accelerometer",
               "android.software.controls",
               "android.hardware.faketouch",
               "android.hardware.telephony.euicc",
               "android.hardware.broadcastradio",
               "android.hardware.usb.accessory",
               "android.software.backup",
               "android.hardware.touchscreen",
               "android.hardware.touchscreen.multitouch",
               "jp.co.sharp.android.software.ime_gbrd",
               "android.software.print",
               "android.software.activities_on_secondary_displays",
               "android.hardware.wifi.rtt",
               "android.software.voice_recognizers",
               "android.software.picture_in_picture",
               "android.hardware.fingerprint",
               "android.hardware.sensor.gyroscope",
               "android.hardware.audio.low_latency",
               "jp.co.sharp.android.software.grsa",
               "android.software.vulkan.deqp.level",
               "android.software.cant_save_state",
               "android.hardware.security.model.compatible",
               "android.hardware.opengles.aep",
               "android.hardware.bluetooth",
               "android.hardware.camera.autofocus",
               "android.hardware.telephony.gsm",
               "android.hardware.telephony.ims",
               "android.hardware.se.omapi.ese",
               "android.software.opengles.deqp.level",
               "android.hardware.usb.host",
               "android.hardware.audio.output",
               "jp.co.sharp.android.felica",
               "android.software.verified_boot",
               "android.hardware.camera.flash",
               "android.hardware.camera.front",
               "android.hardware.se.omapi.uicc",
               "android.hardware.screen.portrait",
               "jp.co.sharp.android.antitok.batterylog",
               "com.google.android.feature.DPS",
               "android.hardware.nfc",
               "com.google.android.feature.TURBO_PRELOAD",
               "com.nxp.mifare",
               "android.hardware.sensor.stepdetector",
               "android.software.home_screen",
               "android.hardware.microphone",
               "android.software.autofill",
               "android.software.securely_removes_users",
               "android.hardware.bluetooth_le",
               "android.hardware.sensor.compass",
               "android.hardware.touchscreen.multitouch.jazzhand",
               "android.software.app_widgets",
               "android.software.input_methods",
               "android.hardware.sensor.light",
               "android.hardware.vulkan.version",
               "android.software.companion_device_setup",
               "android.software.device_admin",
               "com.google.android.feature.WELLBEING",
               "android.hardware.wifi.passpoint",
               "android.hardware.camera",
               "android.hardware.screen.landscape",
               "com.google.android.feature.AER_OPTIMIZED",
               "android.hardware.ram.normal",
               "jp.co.sharp.android.software.karadamate",
               "android.software.managed_users",
               "android.software.webview",
               "android.hardware.sensor.stepcounter",
               "android.hardware.camera.capability.manual_post_processing",
               "com.google.lens.feature.IMAGE_INTEGRATION",
               "jp.co.sharp.android.bluetooth.pbap.pce",
               "android.hardware.camera.any",
               "jp.co.sharp.android.downloadfont_v2",
               "jp.co.sharp.android.fingerprint.gesture",
               "android.hardware.camera.capability.raw",
               "android.hardware.vulkan.compute",
               "android.software.connectionservice",
               "android.hardware.touchscreen.multitouch.distinct",
               "android.hardware.location.network",
               "android.software.cts",
               "android.hardware.camera.capability.manual_sensor",
               "android.software.app_enumeration",
               "android.hardware.camera.level.full",
               "android.hardware.wifi.direct",
               "android.software.live_wallpaper",
               "android.software.ipsec_tunnels",
               "android.hardware.location.gps",
               "android.software.midi",
               "android.hardware.nfc.any",
               "android.hardware.nfc.ese",
               "android.hardware.nfc.hce",
               "android.hardware.wifi",
               "android.hardware.location",
               "android.hardware.vulkan.level",
               "com.google.android.feature.PREMIER_TIER",
               "jp.co.sharp.android.hardware.led",
               "android.software.secure_lock_screen",
               "android.hardware.telephony",
               "android.software.file_based_encryption"
          ],
          "manufacturer": "SHARP",
          "tags": "release-keys",
          "supported64BitAbis": [
               "arm64-v8a"
          ],
          "bootloader": "unknown",
          "fingerprint": "RAKUTEN/SH-RM15/JeridL:12/SA045/03.00.05:user/release-keys",
          "host": "TG691013",
          "model": "SH-RM15",
          "id": "SA045",
          "brand": "RAKUTEN",
          "device": "JeridL",
          "board": "Jerid",
          "hardware": "qcom"
     }
}
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ {
│      "authorId": "usr_42a4ec2c-3759-45e0-99fb-0e05135473cc",
│      "authorName": "ARUSON_EF",
│      "capacity": 32,
│      "created_at": "2022-01-20T05:36:14.017Z",
│      "description": "Mirror ⁄ Video ⁄ QVPen ⁄ AudioLink ⁄ AudioReverbFilter",
│      "favorites": 42115,
│      "featured": false,
│      "heat": 7,
│      "id": "wrld_a1c1d9a3-d8ea-4852-a8f5-5c72f0b98653",
│      "imageUrl": "https://api.vrchat.cloud/api/1/file/file_ec42666e-76cf-44ea-a3f5-ad89e764309d/2/file",
│      "instances": [
│           [
│                "58853~region(jp)",
│                1
│           ],
│           [
│                "75431~region(jp)",
│                13
│           ],
│           [
│                "47017~region(jp)",
│                6
│           ],
│           [
│                "33082~region(jp)",
│                3
│           ],
│           [
│                "99929~region(jp)",
│                1
│           ],
│           [
│                "37697~region(jp)",
│                1
│           ],
│           [
│                "15448~region(jp)",
│                1
│           ]
│      ],
│      "labsPublicationDate": "2023-05-03T13:10:30.683Z",
│      "name": "メゾン荘 201号室",
│      "occupants": 189,
│      "organization": "vrchat",
│      "popularity": 8,
│      "previewYoutubeId": null,
│      "privateOccupants": 146,
│      "publicOccupants": 43,
│      "publicationDate": "2023-05-03T17:27:36.256Z",
│      "recommendedCapacity": 16,
│      "releaseStatus": "public",
│      "storeId": null,
│      "tags": [
│           "author_tag_room",
│           "author_tag_chill",
│           "author_tag_relax",
│           "author_tag_japan",
│           "author_tag_home",
│           "system_approved",
│           "admin_onboarding_japan",
│           "system_updated_recently"
│      ],
│      "thumbnailImageUrl": "https://api.vrchat.cloud/api/1/image/file_ec42666e-76cf-44ea-a3f5-ad89e764309d/2/256",
│      "udonProducts": [],
│      "unityPackages": [
│           {
│                "assetUrl": "https://api.vrchat.cloud/api/1/file/file_7efe5be0-8e40-401c-af72-9f40b969b594/1/file",
│                "assetVersion": 4,
│                "created_at": "2023-06-22T08:55:06.345Z",
│                "id": "unp_d46c5718-96a7-4f38-9dfa-669d742831bf",
│                "platform": "android",
│                "pluginUrl": "",
│                "unitySortNumber": 20190431000,
│                "unityVersion": "2019.4.31f1"
│           },
│           {
│                "assetUrl": "https://api.vrchat.cloud/api/1/file/file_7efe5be0-8e40-401c-af72-9f40b969b594/4/file",
│                "assetVersion": 1,
│                "created_at": "2024-01-13T04:22:10.926Z",
│                "id": "unp_5ff775b7-1a50-4c9c-b218-d38107f05339",
│                "platform": "android",
│                "pluginUrl": "",
│                "unitySortNumber": 20190431000,
│                "unityVersion": "2019.4.31f1"
│           },
│           {
│                "assetUrl": "https://api.vrchat.cloud/api/1/file/file_7efe5be0-8e40-401c-af72-9f40b969b594/6/file",
│                "assetVersion": 4,
│                "created_at": "2024-05-14T05:08:30.923Z",
│                "id": "unp_78bbfef2-b07d-4a51-b1a5-d6cc95ad8143",
│                "platform": "android",
│                "unitySortNumber": 20220306000,
│                "unityVersion": "2022.3.6f1"
│           },
│           {
│                "assetUrl": "https://api.vrchat.cloud/api/1/file/file_7efe5be0-8e40-401c-af72-9f40b969b594/13/file",
│                "assetVersion": 4,
│                "created_at": "2024-09-11T08:59:15.722Z",
│                "id": "unp_0d4e102e-e891-4344-9480-e5288d23260b",
│                "platform": "android",
│                "unitySortNumber": 20220322000,
│                "unityVersion": "2022.3.22f1"
│           },
│           {
│                "assetUrl": "https://api.vrchat.cloud/api/1/file/file_7244e071-f9cd-4b2d-af52-9c0393306c19/16/file",
│                "assetVersion": 4,
│                "created_at": "2023-06-22T09:02:20.643Z",
│                "id": "unp_70155a89-4877-47bf-b700-7c2a75b71925",
│                "platform": "standalonewindows",
│                "pluginUrl": "",
│                "unitySortNumber": 20190431000,
│                "unityVersion": "2019.4.31f1"
│           },
│           {
│                "assetUrl": "https://api.vrchat.cloud/api/1/file/file_7244e071-f9cd-4b2d-af52-9c0393306c19/21/file",
│                "assetVersion": 1,
│                "created_at": "2024-01-13T04:22:32.298Z",
│                "id": "unp_6a699401-d3e2-4803-a417-c27bcb206158",
│                "platform": "standalonewindows",
│                "pluginUrl": "",
│                "unitySortNumber": 20190431000,
│                "unityVersion": "2019.4.31f1"
│           },
│           {
│                "assetUrl": "https://api.vrchat.cloud/api/1/file/file_7244e071-f9cd-4b2d-af52-9c0393306c19/23/file",
│                "assetVersion": 4,
│                "created_at": "2024-05-14T04:59:16.599Z",
│                "id": "unp_935967aa-9916-445e-a93e-40c7056f6de9",
│                "platform": "standalonewindows",
│                "unitySortNumber": 20220306000,
│                "unityVersion": "2022.3.6f1"
│           },
│           {
│                "assetUrl": "https://api.vrchat.cloud/api/1/file/file_7244e071-f9cd-4b2d-af52-9c0393306c19/30/file",
│                "assetVersion": 4,
│                "created_at": "2024-09-11T08:55:15.973Z",
│                "id": "unp_c5b12121-cb74-4584-b142-dbca8230bc9c",
│                "platform": "standalonewindows",
│                "unitySortNumber": 20220322000,
│                "unityVersion": "2022.3.22f1"
│           }
│      ],
│      "updated_at": "2024-09-11T08:59:15.956Z",
│      "version": 53,
│      "visits": 1695230
│ }
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   new VRChatWorld.fromJson (package:vrc_manager/api/data_class.dart:245)
│ #1   VRChatAPI.worlds.<anonymous closure> (package:vrc_manager/api/main.dart:342)
│ #2   <asynchronous suspension>
│ #3   Future.wait.<anonymous closure> (dart:async/future.dart:525)
│ #4   <asynchronous suspension>
│ #5   vrchatMobileUserProvider.<anonymous closure> (package:vrc_manager/scenes/sub/user.dart:57)
│ #6   <asynchronous suspension>
│ #7   FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:337)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ type 'Null' is not a subtype of type 'String'
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by fa0311** [comment]
報告ありがとうございます！`v5.1.0` で修正されました
